title: Blog
author: QYF
email: huangyz0918@gmail.com
description: Hard work always pays off.

# Build settings
remote_theme: huangyz0918/moving
plugins:
  - jekyll-feed

moving:
  about_you: Hard work always pays off
  avatar_url: https://i.loli.net/2019/09/07/wiBh3uMWRUaLX5K.png 
  date_format: "%b %d"
  back_to: "Index"
  social_links:
    rss: RSS
    github:  harryqin99
    linkedin: Yongfeng Qin
