title: Blog
author: QYF
email: harryqinyf@outlook.com
description: Just a blog.
favicon: "./favicon.ico"
url: https://leafy-pastelito-ae786e.netlify.app/

# Build settings
remote_theme: huangyz0918/moving
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-last-modified-at

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%d-%b-%y'

moving:
  about_you: Developer
  avatar_url: "https://i.loli.net/2021/09/19/1eVZ5plD2Ub3XBE.jpg"
  date_format: "%b %d"
  back_to: "Index"
  social_links:
    github:  harryqin99

