title: Blog
author: QYF
email: harryqin1999@gmail.com
description: Just a blog.
favicon: "./favicon.ico"

# Build settings
remote_theme: huangyz0918/moving
plugins:
  - jekyll-feed

moving:
  about_you: A student
  avatar_url: https://i.loli.net/2019/09/07/wiBh3uMWRUaLX5K.png 
  date_format: "%b %d"
  back_to: "Index"
  social_links:
    rss: RSS
    github:  harryqin99
    linkedin: Yongfeng Qin
