title: Blog
author: QYF
email: harryqinyf@outlook.com
description: Just a blog.
favicon: "./favicon.ico"

# Build settings
remote_theme: huangyz0918/moving
plugins:
  - jekyll-feed
  - jekyll-seo-tag

moving:
  about_you: Developer
  avatar_url: "https://i.loli.net/2021/09/19/1eVZ5plD2Ub3XBE.jpg"
  date_format: "%b %d"
  back_to: "Index"
  social_links:
    github:  harryqin99

