title: Blog
author: QYF
email: harryqin1999@gmail.com
description: Just a blog.
favicon: "./favicon.ico"

# Build settings
remote_theme: huangyz0918/moving
plugins:
  - jekyll-feed

moving:
  about_you: Trying to be > or == yesterday
  avatar_url: "https://i.loli.net/2021/09/19/1eVZ5plD2Ub3XBE.jpg"
  date_format: "%b %d"
  back_to: "Index"
  social_links:
    github:  harryqin99
